### PR TITLE
login/signin page added (issue #14)

### PR DESCRIPTION
**Pull request by ronitblenz**
Screenshot 2022-02-11 at 5 06 26 PM
Screenshot 2022-02-11 at 5 06 16 PM

Kindly merge my PR

### CODE REVIEW

**Comment by Codehackerone** [comment]
Hello, your designs are good, but this is an API system. There's no need for HTML pages here. What I said in the issue was to make a route and a controller.

**Comment by ronitblenz** [comment]
Oh, I am actually not aware about route and controller, is it possible to merge this PR, then later can work on the thing you are talking about? Coz, I took much time and effort to build this

**Comment by Codehackerone** [comment]
> Oh, I am actually not aware about route and controller, is it possible to merge this PR, then later can work on the thing you are talking about? Coz, I took much time and effort to build this

I really do appreciate your effort and no doubt it's very good, but this repo only acts as an API system, so this can't be accepted as a PR. You can always make use of this somewhere else, your efforts will not go in vain.

**Comment by ronitblenz** [comment]
> > Oh, I am actually not aware about route and controller, is it possible to merge this PR, then later can work on the thing you are talking about? Coz, I took much time and effort to build this
> 
> I really do appreciate your effort and no doubt it's very good, but this repo only acts as an API system, so this can't be accepted as a PR. You can always make use of this somewhere else, your efforts will not go in vain.

Thank you, I am really happy with your response😊

**Pull request closed without merging**
